### ISSUE TITLE
must record user consent to TOS

### ISSUE THREAD

**Issue by sneak** [steemit/faucet#232]
As a user who signed up via faucet, it is important to steemit that I have agreed to the current version of the TOS before my account is created and that that fact is recorded in the `conveyor` tagging database.

This means the current Steemit TOS needs to be displayed to the user during account creation, and they must agree to it, and then that agreement and TOS version must be recorded via setting a tag on that user via `conveyor`.

**Comment by pkattera** [comment]
On the last step before the account is created:

### Update this:

![confirm-key-1](https://user-images.githubusercontent.com/1121139/37685011-286586ea-2c4f-11e8-9fb3-788d1f3832aa.png)

### To this:

![confirm-key-2](https://user-images.githubusercontent.com/1121139/37685025-3311aef2-2c4f-11e8-9014-ce5a200e6421.png)

### Notes

For simplicity, let's just link people directly to these pages (instead of using a lightbox / modal)
- Terms of Service: https://steemit.com/tos.html
- Privacy Policy: https://steemit.com/privacy.html

### Questions

By default, we'll include Steemit Inc's Terms of Service and Privacy Policy. 

- How should we handle this for third party apps like Busy.org who link their users to the faucet for sign up? We could allow them to include a link to their own TOS and Privacy Policy (similar to how we let these apps inject their logo using the `ref=busy` URL). 
- Is Converyor able to track that the user actually signed up to Busy's TOS and pass that information to Busy for their records?

**Comment by sneak** [comment]
conveyor is, by design, for steemit-specific data only. if other apps want to get users to agree to an additional TOS, they can do it in those other apps.

**Comment by jnordberg** [comment]
Another option is to have the TOS acceptance check in condenser upon login. That decreases faucets steemit tie-in and we are going to need that login check anyway when we want to update the TOS

**Comment by bnchdrff** [comment]
if we want to only enable the ToS links for no-referrer signups, this is blocked by https://github.com/steemit/faucet/issues/328
