### ISSUE TITLE
Remove eslint-enable from signup pages

### ISSUE THREAD

**Issue by cyon1c** [steemit/faucet#286]
`/* eslint-enable */` renders on the signup pages.

![screen shot 2018-04-06 at 3 00 31 pm](https://user-images.githubusercontent.com/2797238/38443857-b8ea10c6-39b2-11e8-8757-20922f03eb49.png)

**Comment by gl2748** [comment]
To fix - I think it would just be making sure the JS comment syntax happens inside  a curly-bracket so that the JSX doesn't think it needs to be rendered to the DOM... That said - addressing whatever eslint was disabled for here ...

https://github.com/steemit/faucet/blob/bf59374e64af4eb1f1709e9adb86820606f2b0fa/src/components/CreateAccount.js#L391-L399

Might be the best solution... It might be possible to remove these altogether.
